server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /env.js {
        alias /config/env.js;
        default_type application/javascript;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}