import type { Product } from '@/domain/product/Product';

export const productSeeds: Product[] = [
  {
    id: 'p1',
    name: 'Lapin Doudou',
    description: 'Adorable lapin en crochet fait main, parfait compagnon pour les tout-petits. Rembourrage hypoallergénique.',
    price: 3500,
    category: 'amigurumi',
    imageUrl: '/images/product-1.jpg',
    colors: ['Rose', 'Beige', 'Gris'],
    isCustomizable: false,
    inStock: true,
    rating: 4.9,
    reviewCount: 47,
  },
  {
    id: 'p2',
    name: 'Écharpe Bohème',
    description: 'Écharpe légère en laine mérinos, motif dentelle au crochet.',
    price: 4200,
    category: 'accessoire',
    imageUrl: '/images/product-2.jpg',
    colors: ['Mauve', 'Écru', 'Terracotta'],
    isCustomizable: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 32,
  },
  {
    id: 'p3',
    name: 'Panier Rangement',
    description: 'Panier décoratif en crochet pour organiser votre intérieur avec style.',
    price: 2800,
    category: 'decoration',
    imageUrl: '/images/product-3.jpg',
    colors: ['Naturel', 'Blanc', 'Gris'],
    isCustomizable: false,
    inStock: true,
    rating: 4.7,
    reviewCount: 28,
  },
  {
    id: 'p4',
    name: 'Gilet Bébé',
    description: 'Gilet en crochet pour bébé, coton doux et hypoallergénique.',
    price: 5500,
    category: 'bebe',
    imageUrl: '/images/product-4.jpg',
    colors: ['Blanc', 'Rose poudré', 'Bleu ciel'],
    isCustomizable: true,
    inStock: true,
    rating: 5.0,
    reviewCount: 19,
  },
  {
    id: 'p5',
    name: 'Coussin Mandala',
    description: 'Coussin décoratif au motif mandala, pièce unique faite main.',
    price: 4200,
    category: 'decoration',
    imageUrl: '/images/product-5.jpg',
    colors: ['Multicolore', 'Mauve', 'Turquoise'],
    isCustomizable: true,
    inStock: true,
    rating: 4.6,
    reviewCount: 23,
  },
  {
    id: 'p6',
    name: 'Bonnet Pompon',
    description: 'Bonnet en crochet avec pompon en fausse fourrure, chaud et confortable.',
    price: 1800,
    category: 'accessoire',
    imageUrl: '/images/product-6.jpg',
    colors: ['Mauve', 'Rose', 'Blanc', 'Gris'],
    isCustomizable: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 41,
  },
  {
    id: 'p7',
    name: 'Sac Bohème',
    description: 'Sac à main en macramé et crochet, style bohème chic.',
    price: 4500,
    category: 'accessoire',
    imageUrl: '/images/product-7.jpg',
    colors: ['Naturel', 'Mauve', 'Noir'],
    isCustomizable: true,
    inStock: true,
    rating: 4.9,
    reviewCount: 36,
  },
  {
    id: 'p8',
    name: 'Chaussons Bébé',
    description: 'Chaussons en crochet pour bébé de 0 à 6 mois, doux et confortables.',
    price: 1500,
    category: 'bebe',
    imageUrl: '/images/product-8.jpg',
    colors: ['Mauve', 'Blanc', 'Rose'],
    isCustomizable: false,
    inStock: true,
    rating: 4.8,
    reviewCount: 55,
  },
];
