import type { Order } from '@/domain/order/Order';

export const orderSeeds: Order[] = [
  {
    id: 'CMD-2024-001',
    items: [
      { productId: 'p1', productName: 'Lapin Doudou', unitPrice: 3500, quantity: 1, imageUrl: '/images/product-1.jpg' },
      { productId: 'p2', productName: 'Écharpe Bohème', unitPrice: 4200, quantity: 1, imageUrl: '/images/product-2.jpg' },
    ],
    total: 7700,
    status: 'in_progress',
    createdAt: new Date('2024-12-01'),
    customerName: 'Amina B.',
    customerPhone: '0555 12 34 56',
    customerAddress: '12 Rue Didouche Mourad',
    customerCity: 'Alger',
    steps: [
      { status: 'pending', label: 'Commande reçue', date: new Date('2024-12-01'), completed: true },
      { status: 'confirmed', label: 'Confirmée', date: new Date('2024-12-02'), completed: true },
      { status: 'in_progress', label: 'En fabrication', date: new Date('2024-12-05'), completed: true },
      { status: 'shipped', label: 'Expédiée', completed: false },
      { status: 'delivered', label: 'Livrée', completed: false },
    ],
  },
  {
    id: 'CMD-2024-002',
    items: [
      { productId: 'p4', productName: 'Gilet Bébé', unitPrice: 5500, quantity: 2, imageUrl: '/images/product-4.jpg' },
    ],
    total: 11000,
    status: 'shipped',
    createdAt: new Date('2024-11-20'),
    customerName: 'Sara M.',
    customerPhone: '0661 98 76 54',
    customerAddress: '45 Boulevard Krim Belkacem',
    customerCity: 'Oran',
    steps: [
      { status: 'pending', label: 'Commande reçue', date: new Date('2024-11-20'), completed: true },
      { status: 'confirmed', label: 'Confirmée', date: new Date('2024-11-21'), completed: true },
      { status: 'in_progress', label: 'En fabrication', date: new Date('2024-11-25'), completed: true },
      { status: 'shipped', label: 'Expédiée', date: new Date('2024-12-01'), completed: true },
      { status: 'delivered', label: 'Livrée', completed: false },
    ],
  },
  {
    id: 'CMD-2024-003',
    items: [
      { productId: 'p7', productName: 'Sac Bohème', unitPrice: 4500, quantity: 1, imageUrl: '/images/product-7.jpg' },
      { productId: 'p6', productName: 'Bonnet Pompon', unitPrice: 1800, quantity: 3, imageUrl: '/images/product-6.jpg' },
    ],
    total: 9900,
    status: 'delivered',
    createdAt: new Date('2024-10-15'),
    customerName: 'Lina K.',
    customerPhone: '0770 55 44 33',
    customerAddress: '8 Rue Larbi Ben M\'hidi',
    customerCity: 'Constantine',
    steps: [
      { status: 'pending', label: 'Commande reçue', date: new Date('2024-10-15'), completed: true },
      { status: 'confirmed', label: 'Confirmée', date: new Date('2024-10-16'), completed: true },
      { status: 'in_progress', label: 'En fabrication', date: new Date('2024-10-20'), completed: true },
      { status: 'shipped', label: 'Expédiée', date: new Date('2024-10-28'), completed: true },
      { status: 'delivered', label: 'Livrée', date: new Date('2024-11-02'), completed: true },
    ],
  },
  {
    id: 'CMD-2024-004',
    items: [
      { productId: 'p3', productName: 'Panier Rangement', unitPrice: 2800, quantity: 1, imageUrl: '/images/product-3.jpg' },
    ],
    total: 2800,
    status: 'pending',
    createdAt: new Date('2024-12-10'),
    customerName: 'Nadia R.',
    customerPhone: '0550 11 22 33',
    customerAddress: '22 Cité des Oliviers',
    customerCity: 'Blida',
    steps: [
      { status: 'pending', label: 'Commande reçue', date: new Date('2024-12-10'), completed: true },
      { status: 'confirmed', label: 'Confirmée', completed: false },
      { status: 'in_progress', label: 'En fabrication', completed: false },
      { status: 'shipped', label: 'Expédiée', completed: false },
      { status: 'delivered', label: 'Livrée', completed: false },
    ],
  },
  {
    id: 'CMD-2024-005',
    items: [
      { productId: 'p5', productName: 'Coussin Mandala', unitPrice: 4200, quantity: 2, imageUrl: '/images/product-5.jpg' },
      { productId: 'p8', productName: 'Chaussons Bébé', unitPrice: 1500, quantity: 1, imageUrl: '/images/product-8.jpg' },
    ],
    total: 9900,
    status: 'confirmed',
    createdAt: new Date('2024-12-08'),
    customerName: 'Yasmine T.',
    customerPhone: '0699 88 77 66',
    customerAddress: '5 Rue des Frères Bouadou',
    customerCity: 'Tizi Ouzou',
    steps: [
      { status: 'pending', label: 'Commande reçue', date: new Date('2024-12-08'), completed: true },
      { status: 'confirmed', label: 'Confirmée', date: new Date('2024-12-09'), completed: true },
      { status: 'in_progress', label: 'En fabrication', completed: false },
      { status: 'shipped', label: 'Expédiée', completed: false },
      { status: 'delivered', label: 'Livrée', completed: false },
    ],
  },
];
